import Head from 'next/head'
import Image from 'next/image'
import Signin from '../src/component/Signin'
import TopLogo from '../src/component/TopLogo'
import TopMenuBar from '../src/component/TopMenuBar'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopLogo />
      <TopMenuBar />

      <main className={styles.main}>
        {/* 
        Spring boot server 의 경로를 호출하여
        받은 자원들을 표현할 컴포넌트 호출
        
        */}
        <span>main body contents</span>
        {/* <GetEmployeeListWithPaging elist={elist} /> */}

        <Signin />
        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
